### ISSUE TITLE
Configure microarchitecture by config file

### ISSUE THREAD

**Issue by ryukzak** [ryukzak/nitta#82]
CLI: ```nitta --microarchitecture=ma.toml```

Unmarshalling should be implemented in https://github.com/ryukzak/nitta/blob/master/src/NITTA/Model/Microarchitecture.hs . 

How to work with toml: https://github.com/ryukzak/nitta/blob/ref-target-project-generatino/src/NITTA/Project/Template.hs

Config example:
```toml
[microarchitecture]

[microarchitecture.net1]
type = "FX32.32"

[microarchitecture.net1.accum]
type = "accum"

[microarchitecture.net1.mul]
type = "multiplier"
mock = true

[microarchitecture.net1.div]
type = "divider"

[microarchitecture.net1.spi]
type = "spi"
mode = "slave"
mosi="mosi"
miso="miso"
sclk="sclk"
cs="cs"

[microarchitecture.net1.fram1]
type = "fram"
size = 16

[microarchitecture.net1.fram2]
type = "fram"
size = 32
```

Which should be equal to + bus type declaration:
```haskell
microarch :: IOSynchronization -> BusNetwork String String (Attr (FX 32 32)) Int)
microarch ioSync = defineNetwork "net1" ioSync $ do
    addCustom "fram1" (framWithSize 16) FramIO
    addCustom "fram2" (framWithSize 32) FramIO
    add "shift" ShiftIO
    add "mul" MultiplierIO
    add "accum" AccumIO
    add "div" DividerIO
    add "spi" $
        SPISlave
            { slave_mosi = InputPortTag "mosi"
            , slave_miso = OutputPortTag "miso"
            , slave_sclk = InputPortTag "sclk"
            , slave_cs = InputPortTag "cs"
            }
```
